import React, { useState } from 'react';
import styles from '@/styles/Chat.module.css'
import Head from 'next/head';
import Link from 'next/link';
import { AuthContextProvider } from '@/utils/AuthContext';

function Chat() {
    const [messages, setMessages] = useState([{ sender: "Bot", value: "Hello there! Ask me a question." }]);
    const [inputValue, setInputValue] = useState('');

    const handleInputChange = (event) => {
        setInputValue(event.target.value);
    }

    const handleFormSubmit = (event) => {
        event.preventDefault();
        if (inputValue.trim() !== '') {
            setMessages([...messages, { sender: "Sender", value: inputValue }]);
            setInputValue('');
        }
    }

    return (
        <AuthContextProvider>
            <Head>
                <title>CeladonAI | Personalised ChatGPT for your brand</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.Chat}>
                <div className={styles.top}>
                    <h3><Link href="/"><button className={styles.back}>Go Back</button></Link> Bot 4</h3>
                </div>
                <div className={styles.messageContainer}>
                    <div className={styles.messages}>
                        {messages.map((message, index) => (
                            <div className={styles.message} key={index}>
                                <strong style={{ textDecoration: "underline" }}>{message.sender}</strong>: {message.value}
                            </div>
                        ))}
                    </div>
                    <form className={styles.form} onSubmit={handleFormSubmit}>
                        <input
                            type="text"
                            value={inputValue}
                            onChange={handleInputChange}
                            placeholder="Type your message..."
                            className={styles.input}
                        />
                        <button className={styles.button} type="submit">Send</button>
                    </form>
                </div>
            </div>
        </AuthContextProvider>
    );
}

export default Chat;
