import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar';
import { AuthContextProvider } from '/utils/AuthContext'
import UploadForm from '@/components/UploadForm';

export default function Home() {
    return (
        <AuthContextProvider>
            <div className={styles.home}>
                <Head>
                    <title>CeladonAI | Personalised ChatGPT for your brand</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Navbar />
                <div className={styles.container}>
                    <div style={{
                        display: "flex",
                        flexDirection: "row",
                        justifyContent: "space-evenly",
                        alignItems: "center",
                        width: "100%"
                    }}>

                        <div className={styles.landingContent}>
                            <h1 style={{ fontSize: 50 }}>Train and leverage <span style={{color: "black"}}>custom chatbots to boost productivity</span></h1>
                        </div>
                        <div style={{
                            flex: 1,
                            justifyContent: "center",
                            alignItems: "center",
                            padding: 50
                        }}>
                            <p>Start by uploading a file to train your chatbot</p>
                            <UploadForm/>
                        </div>
                    </div>
                </div>
            </div>
        </AuthContextProvider>
    )
}