import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';

export default function Home() {
    const [selectedFile, setSelectedFile] = useState(null);

    const handleFileUpload = (event) => {
        const file = event.target.files[0];
        setSelectedFile(file);
    };

    const handleSubmit = (event) => {
        event.preventDefault();

        if (selectedFile) {
            // Perform file upload logic here
            console.log('Uploading file:', selectedFile);
        } else {
            console.log('Please select a file.');
        }
    }

    return (
        <>
            <Head>
                <title>CeladonAI | Personalised ChatGPT for your brand</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <h1 className={styles.title}>Welcome to <strong style={{color: "#1824c0", fontFamily: "monospace"}}>CeladonAI</strong></h1>
                <p>Start by uploading a file to train your first chatbot</p>
                <div className={styles.inner}>
                    <form onSubmit={handleSubmit} className={styles.uploadForm}>
                        <input type="file" onChange={handleFileUpload} className={styles.fileInput} />
                        <button type="submit" className={styles.uploadButton}>Upload</button>
                    </form>
                </div>
            </div>
        </>
    )
}