import React from 'react';
import styles from '../../styles/Dashboard.module.css';
import Head from 'next/head';
import Link from 'next/link';
import Navbar from '@/components/Navbar';

const Dashboard = () => {
    return (
        <div>
            <div className={styles.dashboard}>
                <Head>
                    <title>CeladonAI | Personalised ChatGPT for your brand</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <Navbar/>

                <h2 style={{ textAlign: "center", color: "grey" }}>Coming Soon</h2>

                {/* <div className={styles.container}>
                <h3>Your Chat Bots <Link href="/"><button className={styles.button}>Add new</button></Link></h3>
                <br/>
                <Link href="/chat" className={styles.item}>
                    <h3>Bot 1</h3>
                </Link>
                <Link href="/chat" className={styles.item}>
                    <h3>Bot 2</h3>
                </Link>
                <Link href="/chat" className={styles.item}>
                    <h3>Bot 3</h3>
                </Link>
                <Link href="/chat" className={styles.item}>
                    <h3>Bot 4</h3>
                </Link>
            </div> */}
            </div>
        </div>
    );
};

export default Dashboard;